### ISSUE TITLE
TREEP TOKEN BLOCKCHAIN MISSING WALLETS

### ISSUE THREAD

**Issue by zendronfilipe** [stellar-expert/stellar-expert-explorer#514]
Hi, I noticed that when i research for "asset Holders" at treep token asset, there are 2 hidden wallets

GAHVYMDI2HPEDNL57HRHW6VPO7TQDNULFVYOC4D5XQAQRQID2IXN2C3R

and

GCY43FKQYFMOBSDPQOVOPDAT3VI2PVAGPSRLWQDFCB45O3B2DV6AMLFB

Can you check it and fix it? 
you can check by the imagem attached that the ranking goes from 16 to 18, it not appear the 17 wallet

![IMAGE 2021-08-04 17:21:41](https://user-images.githubusercontent.com/88459640/128249414-0c07fcf6-180d-4d28-8049-fed915e42a41.jpg)

**Comment by zendronfilipe** [comment]
This Wallet is missing once again, whats is wrong? 

GCY43FKQYFMOBSDPQOVOPDAT3VI2PVAGPSRLWQDFCB45O3B2DV6AMLFB

![Captura de Tela 2021-08-09 às 15 21 32](https://user-images.githubusercontent.com/88459640/128754864-abce3c7a-b4ee-4c6a-962c-48ba7e2ddbb6.png)

**Comment by orbitlens** [comment]
Hello,

We have to precompute balances and account ranks because directly querying the database is too slow in this case. Since the recalculation process runs once in a while, some accounts may disappear from the list or show up with invalid rank. We are actively working on other approaches to this non-trivial problem, but it takes time. Maybe a week or two.

Sorry for the inconvenience.
