### ISSUE TITLE
remove scam label from address

### ISSUE THREAD

**Issue by ScalableIntegration** [stellar-expert/stellar-expert-explorer#761]
Hello XLM explorer team!
My name is Janna and I represent the Scalable team which is a tech solutions provider for HitBTC. We are taking care of all development and maintenance for HitBTC.
We have a problem - our address is marked as SCAM connected account for some reason according to your explorer:
https://stellar.expert/explorer/public/account/GD5NP74FP22VVRVPUFWONJVXTMK64R4Y6EEJZYW6JNKDTPK4TR6HR6OT
Can you please help us and remove it asap? It confusing our users.

**Comment by CryptoHobbyist** [comment]
Hello Janna,

@orbitlens can correct my mistake. It is a wallet that many scammers had funneled stolen XLM through, and since there were not any memos and it was not tagged as a HitBTC wallet I mistakenly Tagged it as a "Serial SCAM Minter's connected account". 

@orbitlens can you change the tag to HitBTC exchange  (HitBTC.com). Or @ScalableIntegration if you have a different tag to use please let us know.

**Comment by orbitlens** [comment]
> Hello Janna,
> 
> @orbitlens can correct my mistake. It is a wallet that many scammers had funneled stolen XLM through, and since there were not any memos and it was not tagged as a HitBTC wallet I mistakenly Tagged it as a "Serial SCAM Minter's connected account".
> 
> @orbitlens can you change the tag to HitBTC exchange (HitBTC.com). Or @ScalableIntegration if you have a different tag to use please let us know.

Done

**Comment by ScalableIntegration** [comment]
@orbitlens @CryptoHobbyist  We will appreciate if you mark this address as Union Chain.
Thank you for your support!
